# Generated by Django 5.1.1 on 2024-10-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=128)),
                ('pictureurl', models.CharField(max_length=50)),
            ],
        ),
    ]
