# Generated by Django 5.1.1 on 2024-10-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='pictureurl',
            field=models.CharField(max_length=20),
        ),
    ]
